name: Request Daily Egg Data

on:
  push:
    branches:
      - main  # Run the pipeline only on pushes to the main branch

jobs:
  run-daily-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Use the version of Python compatible with your project

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Daily Email Script
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python daily.py

    - name: Debug Environment Variables
      run: echo $EMAIL_ADDRESS
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
